- hosts: ansible_host
  gather_facts: no

  tasks:
    - name: Login to Docker Hub
      docker_login:
        username: na3150
        password: "{{ lookup('env', 'PASS') }}"
        reauthorize: yes

    - name: Build and Push Image
      docker_image:
        build:
          path: /home/ubuntu/mini4-introduction
        name: na3150/mini4-introduction
        tag: "{{ lookup('env', 'BUILD_NUMBER') }}"
        push: yes
        source: build
